<?php

namespace AppBundle\Repository;

/**
 * OrganizationUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationUnitRepository extends \Doctrine\ORM\EntityRepository
{

}
