tds:
    resource: "@TdsBundle/Controller/"
    type:     annotation
    prefix:   /
settings:
    resource: "@SettingsBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
