# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.tds_voter:
        class: TdsBundle\Security\TdsVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.token_authenticator:
        class: TdsBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@session']