<?php

namespace TdsBundle\Repository;

/**
 * TdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TdsRepository extends \Doctrine\ORM\EntityRepository
{
}
