<?php

namespace SettingsBundle\Repository;

/**
 * TrademarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrademarkRepository extends \Doctrine\ORM\EntityRepository
{

}
